drop view if exists public.public_dance_cards;
drop function if exists public.record_admin_action(text, text, text, text);
drop policy if exists admin_logs_admin_read on public.admin_action_logs;
drop policy if exists dance_cards_admin_all on public.dance_cards;
drop policy if exists dance_cards_owner_update on public.dance_cards;
drop policy if exists dance_cards_owner_insert on public.dance_cards;
drop policy if exists dance_cards_owner_read on public.dance_cards;
drop policy if exists dance_cards_public_read on public.dance_cards;
drop policy if exists studios_admin_write on public.studios;
drop policy if exists studios_admin_read on public.studios;
drop policy if exists studios_public_read on public.studios;
drop policy if exists districts_admin_write on public.districts;
drop policy if exists districts_admin_read on public.districts;
drop policy if exists districts_public_read on public.districts;
drop policy if exists cities_admin_write on public.cities;
drop policy if exists cities_admin_read on public.cities;
drop policy if exists cities_public_read on public.cities;
drop policy if exists identities_select_own_or_admin on public.user_identities;
drop policy if exists users_update_own_or_admin on public.users;
drop policy if exists users_select_own_or_admin on public.users;
drop trigger if exists dance_cards_protect_ownership on public.dance_cards;
drop trigger if exists users_protect_privileged_fields on public.users;
drop function if exists public.protect_dance_card_ownership();
drop function if exists public.protect_user_privileged_fields();
drop function if exists public.is_dance_card_public(uuid, uuid, text, text, timestamptz, date);
drop function if exists public.ensure_current_business_user();
